### ISSUE TITLE
Bug in saving total & Max votes

### ISSUE THREAD

**Issue by actual-saurabh** [averta-lab/feature-request#2]
Ref: https://wordpress.org/support/topic/bug-in-saving-total-and-max-votes

**Comment by baselbers** [comment]
#3 is still "Open". It would be great if this problem will be fixed.

**Comment by n0xew** [comment]
Thanks @actual-saurabh for this fix!

**Comment by hosein71** [comment]
This issue is fixed in version 1.2.0
